language: node_js
node_js:
- '0.10'
- '0.11'
- 'iojs'
before_script:
- npm install -g grunt-cli
- "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
matrix:
  allow_failures:
  - node_js: '0.11'
notifications:
  slack:
    secure: lc8VLmVuHMlUCFQ+TADoXEPCf9byr+mu65aEeFyiP3DBfktHad/YmmU5sUiR1ut/PXqhkjFeZ0gFjNAo3q7R7RJW4cinTncgsG1ZSPY0PH6LyQ+Va2gIDRvyw854Yi58sbPzAxybtgSS9K3QntyRo0kGsGTO4eDAbqzwPLIxZ/Y=
